### ISSUE TITLE
"Issue" in Readme file (Replace only character in documentation)

### ISSUE THREAD

**Issue by mugan86** [lokenxo/ng2-fittext#1]
I test with Angular 4.

On the line "import {Ng2FittextModule} from "ng2-fittext/**ng2-fittext**";" lo correcto sería import {Ng2FittextModule} from "ng2-fittext/**ng2fittext**";

**Comment by thisloke** [comment]
Gracias por la nota, corregido inmediatamente.

**Comment by mugan86** [comment]
👍👍👍👏
