### ISSUE TITLE
Angular v18

### ISSUE THREAD

**Issue by PedroS5499** [lokenxo/ng2-fittext#106]
this npm package has peer dependency on angular v17

`npm i
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: ng2-fittext@1.4.3
npm error Found: @angular/common@18.0.6
npm error node_modules/@angular/common
npm error   @angular/common@"^18.0.6" from the root project
npm error   peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.0.6
npm error   node_modules/@angular/cdk
npm error     @angular/cdk@"^18.0.6" from the root project
npm error     peer @angular/cdk@"18.0.6" from @angular/material@18.0.6
npm error     node_modules/@angular/material
npm error       @angular/material@"^18.0.6" from the root project
npm error   10 more (@angular/forms, @angular/material, ...)
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"^17.0.0" from ng2-fittext@1.4.3
npm error node_modules/ng2-fittext
npm error   ng2-fittext@"^1.4.3" from the root project
npm error
npm error Conflicting peer dependency: @angular/common@17.3.11
npm error node_modules/@angular/common
npm error   peer @angular/common@"^17.0.0" from ng2-fittext@1.4.3
npm error   node_modules/ng2-fittext
npm error     ng2-fittext@"^1.4.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by foerster** [comment]
+1    I need this as well.

**Comment by thisloke** [comment]
Issue fixed, new version of the library released here --> https://www.npmjs.com/package/ng2-fittext

As also other library does, i'm starting now to manage major release like this upgrading the version according to SemVer (https://semver.org/), i was a little bit busy (and lazy) and i always tracked major release a minor release.

I've also updated the [installing section](https://github.com/thisloke/ng2-fittext/blob/master/README.md#installation) in the README.md file to permit to understand which version of the library you need to install.. 

to make it shorter: **if angular  >= 18 --> npm i ng2-fittext@2.0.0**

**Comment by thisloke** [comment]
@PedroS5499 @foerster  let me know if it solve the issue for you.

**Comment by thisloke** [comment]
@PedroS5499 @foerster  let me know if it solve the issue for you.

**Comment by foerster** [comment]
> @PedroS5499 @foerster let me know if it solve the issue for you.

Yes, I was able to complete my angular 18 upgrade. Thank you!

**Comment by PedroS5499** [comment]
> @PedroS5499 @foerster let me know if it solve the issue for you.

Hi @thisloke , Yes. Thanks for quick response and solution ;)
