### ISSUE TITLE
Vertial Align text to center / middle

### ISSUE THREAD

**Issue by dodomui** [lokenxo/ng2-fittext#108]
Hi, When having dynamic multi lines content, having issue to vertical the text to center.
Try flex, table, absolute method all will make ng2-fittext doesn't work properly to auto resize / resize to single line text only.

**Comment by thisloke** [comment]
Hi @dodomui, thanks for reporting it.
In order to address correctly the issue i need to be able to replicate it, can you please provide a working example with https://stackblitz.com or in a repo?

**Comment by dodomui** [comment]
@thisloke do you try vertical align the text before?

**Comment by thisloke** [comment]
There are many ways to center a text vertically (on y-axis), it depends on your implementation, that could different from mine.

Anyway, i will help you, but i need to know exactly what's the problem and how to replicate, so sharing the code could be a really good starting point :)

**Comment by dodomui** [comment]
@thisloke sorry for taking your time. Just notice is not related to ng2-fittext, after trying here.
https://stackblitz.com/edit/stackblitz-starters-ywpjgb?file=src%2Fmain.ts

Must be somewhere in my code restrict the vertical alignment.

Thanks a lot
