### ISSUE TITLE
Angular 4.3.5 compatibility

### ISSUE THREAD

**Issue by martinduris** [lokenxo/ng2-fittext#12]
Hi,
i have upgraded angular in my project to version 4.3.5 and when i run 'ng serve' command i get :

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in .../node_modules/ng2-fittext/node_modules/@angular/core/core.d.ts, resolving symbol Ng2FittextModule in .../node_modules/ng2-fittext/src/ng2fittext.module.ts, resolving symbol Ng2FittextModule in .../node_modules/ng2-fittext/src/ng2fittext.module.ts`

version of ng2-fittext: 1.0.23

Do you have any idea how to fix this problem ?

Thank you !

**Comment by nischi** [comment]
For me it works with 4.3.6. Can you try to update Angular again?

**Comment by martinduris** [comment]
True ! sorry guys, works good, my mistake :-(
