### ISSUE TITLE
ModelToWatch not wokring

### ISSUE THREAD

**Issue by WilliamRitson** [lokenxo/ng2-fittext#14]
I am trying to use this in a card game, in which a card's text may change dynamically. Unfortunately, I haven't been able to get the modelToWatch attribute working.  My html looks like this.

<xhtml:p xmlns="http://www.w3.org/1999/xhtml" 
       fittext="true" activateOnResize="true" [modelToWatch]="card.getText()"
       useMaxFontSize="false"  class="card-text" [innerHTML]="htmlText(card.getText())">
      </xhtml:p> 

When the card's text changes, even if it is clearly overflowing its container, it does not shrink (it is not at the minimum font size, so that shouldn't be a problem).

I was also unable to get it working with a simple boolean value which controls if a card is scaled up or not.  Ideally, I would like the text to shrink if it gets longer, but expand when the card is scaled up.

**Comment by WilliamRitson** [comment]
I investigated a bit more. I was able to get it to work this by changing the line
`setTimeout(_ =>  this.ngAfterViewInit());`
to 
```
setTimeout(_ => {
        this.done = false; 
        this.ngAfterViewInit()
      });
```
Without this modification, I think it can only work once (which is fine if you are loading something from the server once, but doesn't work with data that may change many times). 

But it would only go down in size, never up. So I changed it one more time to
```
setTimeout(_ => {
        this.done = false; 
        this.setFontSize(this.maxFontSize);
        this.ngAfterViewInit()
      });
```
Which works for my purposes, but I don't know the library well enough to say if there is a good reason not to do it that way.

**Comment by sebastientromp** [comment]
Would love to have this work as well

**Comment by thisloke** [comment]
> Would love to have this work as well

Soon, i hope, it depends on my free time.

If you have an implemented solution feel free to pull request.

**Comment by thisloke** [comment]
I'm writing a new  version of the library right now, i've included this fix.

**Comment by thisloke** [comment]
@sebastientromp @WilliamRitson Fix in new version just published. (**1.2.0**)

**Comment by sebastientromp** [comment]
Works perfectly, thanks a lot for the amazing reactivity :)
