### ISSUE TITLE
not resizing in the beginning

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [lokenxo/ng2-fittext#15]
Hello,

I've tried your component however I seem to have an issue with it.
If I use it:
`<div class="information-input-2row" style="width:100px;color:black;background-color: rgba(0, 0, 0, 0.1);white-space: nowrap;" #base_1 [container]="base_1" [fittext]="true" [activateOnResize]="true" [modelToWatch]="currentInfoModel">{{currentInfoModel?.base_1 | removeUndefined}}</div>`

When the value of the model.base_1 goes from "" to "something" this something is displayed gigantically. only after resizing the browserwindow manually the text is resized.

Also, seems that resizing the window is seriously slow. Probably an eventlistener which is not debounced?

Kind regards,

lander

**Comment by thisloke** [comment]
@LanderBeeuwsaert Fix in new version just published. (**1.2.0**)
