### ISSUE TITLE
Broken in angular6?

### ISSUE THREAD

**Issue by LastRose** [lokenxo/ng2-fittext#19]
Upgraded from angular5 to angular6 and this package stopped working
Getting the following warnings

ng2-fittext@1.1.1 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-fittext@1.1.1 requires a peer of @angular/compiler@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-fittext@1.1.1 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-fittext@1.1.1 requires a peer of @angular/platform-browser@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-fittext@1.1.1 requires a peer of @angular/platform-browser-dynamic@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-fittext@1.1.1 requires a peer of rxjs@^5.0. You must install peer dependencies yourself.

**Comment by LastRose** [comment]
It might have something to do with "Anywhere you use Renderer, now use Renderer2"

**Comment by thisloke** [comment]
Thanks for the notify, I think I will fix very soon :)

**Comment by thisloke** [comment]
@LastRose Fix in new version just published. (**1.2.0**)
