### ISSUE TITLE
Max. Font Size?

### ISSUE THREAD

**Issue by RedEars** [lokenxo/ng2-fittext#2]
Hey there, 
is it possible to set some max font size? Or to just change Font size if text does not fit?
I have a grid with menu labels where fittext is set. It works, but it makes the label font-size also bigger which I dont want. Just smaller to fit in the grid column if its a long text label. 

Greetings

**Comment by thisloke** [comment]
Currently is not possible, but i can add the max font size parameter in my next release. 
I think i'm not really understand your problem, the font autoscale depending of the DOM element passed as parameter in the "container" proprierty.

Can you send me a screenshot or better a snippet where I can see the problem?
