### ISSUE TITLE
Problem with a bootstrap carousel

### ISSUE THREAD

**Issue by markolyden** [lokenxo/ng2-fittext#30]
I use this with bootstrap carousel to fit different lengths of text to fit, especially responsively on mobile site. The problem is that the feature does not activate until I scroll the site downwards. Any idea for this?

Also another question, I used previously the useMaxFontSize, and maybe it helped with this problem. Is there some reason why this was removed?

Thanks?

**Comment by thisloke** [comment]
Hi!

Can you provide a snippet of your code?

The useMaxFontSize prop was removed because now the directive have the maxFontSize prop, that works in the same way. You can specify the maxFontSize and also thge minFontSize you want and the text will fit the parent box using that values as min and max.

**Comment by markolyden** [comment]
Hard to say the reason, I had problems with the carousel sliding itself after updating multiple packages from npm, and the reason was found out to be in CSS, something had changed and my custom CSS caused the sliding effect to bounce to another row. Maybe this is related as well, but I haven't found out the reason yet.

```
<div class="event-slider">
    <div id="carouselEvents" *ngIf="events && events.length > 0" class="carousel slide" data-ride="carousel">
        <div *ngIf="events" class="carousel-inner">
            <div *ngFor="let event of events; first as isFirst" class="carousel-item" [class.active]="isFirst">
                <span class="one-line"><i>Tuleva tapahtuma:</i></span>
                <div class="d-sm-none one-line" [fittext]="true" [maxFontSize]="21" [modelToWatch]="event.name"><b>{{event.name}}</b></div>
                <div class="d-none d-md-block one-line" [fittext]="true" [maxFontSize]="30" [modelToWatch]="isFirst"><b>{{event.name}}</b></div>
                <span class="one-line">{{event.startDateTime | date: 'dd.MM.yyyy HH:mm'}}</span>
                <div class="one-line">
                    <a *ngIf="authService.loggedIn()" routerLink="/events/{{event.id}}">Lue lisää</a>
                </div>
            </div>
        </div>        
        <a class="carousel-control-prev" href="#carouselEvents" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselEvents" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
```
