### ISSUE TITLE
Font-size: 0px

### ISSUE THREAD

**Issue by edmondko** [lokenxo/ng2-fittext#4]
For some reason the plugin returns font-size: 0px which is useless even if it breaks the code. 
`<owl-carousel
    #carousel
    [options]="{items: 1, dotsContainer: '.owl-dots', navigation: false, loop: true, lazyLoad: false, autoplay: true,  autoplayTimeout: 5000, autoplayHoverPause: true }">
    <div class="slide" *ngFor="let slide of slides">
      <div class="content">
        <div class="title" #titleRef>
          <span [fittext]="true" [activateOnResize]="true" [container]="titleRef">{{slide.title}}</span>
        </div>
        <div class="text" [innerHtml]="slide.text"></div>
      </div>
    </div>
  </owl-carousel>`
In the output source html I get: 
`
<div _ngcontent-c2="" class="title">
          <span _ngcontent-c2="" ng-reflect-fittext="true" ng-reflect-container="[object HTMLDivElement]" ng-reflect-activate-on-resize="true" style="font-size: 0px; will-change: content;">Microsoft Genuine Font Support</span>
        </div>
`

The plugin shouldn't return 0 even if there's not enough; The container element has a size of 100% screen width and height of 30px

**Comment by thisloke** [comment]
Hi, 
I can't reproduce it with the code you wrote me. 
Can you send me a plunker where i can see this issue? 
You can use this as base http://plnkr.co/edit/v0TQaYepV4E2Heur02j5?p=preview

Lorenzo I.

**Comment by nischi** [comment]
I had a similar problem. I had the problem that the contianer had no height because the children had a float in it. Maybe you have the same problem. check in Browsers Dev-Tools if the container has the correct height to check the calculation.

**Comment by thisloke** [comment]
Thanks to nischi for the solution. 

@edmondko Let me know if your problem was solved upgrading the library.

Thanks!
