### ISSUE TITLE
Works great but when update model I need to refresh.

### ISSUE THREAD

**Issue by carraroinfame** [lokenxo/ng2-fittext#8]
Hi,
the module works great but if I update model with a service the text doesn't fit.
I need a polish way to resize after update model.

I try with resize event but for some reason I can't use this.

**Comment by martinduris** [comment]
Hi guys,
any update ? :-)

so far i can use something like:
`setTimeout(function(){window.dispatchEvent(new Event('resize'));}, 1000);`
but that is not very "nice".

thanks a lot !

**Comment by thisloke** [comment]
Hi! I'm really busy in these days, I'll promise I will fix it in September :) 

If you or anyone have a solution, can submit a merge request.

**Comment by martinduris** [comment]
Hi,
Please check this PR
https://github.com/lokenxo/ng2-fittext/pull/10
thanks
